[JU-26] generateBookRecommendations method
archis-academy/june-backend-lms-2 pull request #24
Opened 2024-07-17 07:54 UTC by yusrayalavuz

2024-07-17 12:39 UTC, furkanErenoglu approved these changes

2024-07-17 12:41 UTC, furkanErenoglu requested changes

2024-07-17 12:41 UTC, furkanErenoglu commented on src/Main.java
> +        addBook("123456789", "Book Title 1", "Author 1", "Additional Info 1");
bunları silerek pushlamaız daha iyi olur

2024-07-17 12:41 UTC, furkanErenoglu commented on src/Main.java
> +                    return;
Burda neden break kullanmadın

2024-07-17 14:47 UTC, yusrayalavuz commented on src/Main.java
> +        addBook("123456789", "Book Title 1", "Author 1", "Additional Info 1");
tamamdır. test ederken kullanmıştım. silmeyi unutmuşum.

2024-07-17 14:49 UTC, yusrayalavuz commented on src/Main.java
> +                    return;
break kullanınca alttaki randomu da çalıştırıyor. yani hem lastBookAuthor varsa o yazarın başka bir kitabını öneriyor. hemde hemen ardından random bir kitap öneriyor. ama return ile direkt metodu sonlandırıyor.

2024-07-17 16:53 UTC, furkanErenoglu commented on src/Main.java
> +                    return;
Süpersin bu cevabı verebilmeni istemiştim :) güncellemelerden sonra pushlayabilirsin

2024-07-17 16:53 UTC, furkanErenoglu commented on src/Main.java
> +                    return;
Süpersin bu cevabı verebilmeni istemiştim :) güncellemelerden sonra pushlayabilirsin

2024-07-18 08:38 UTC, yusrayalavuz commented on src/Main.java
> +                    return;
:) 👍

2024-07-18 08:45 UTC, merged